name: hakai-segmentation
channels:
  - defaults
dependencies:
  - python=3.9
  - conda-forge::fire
  - conda-forge::numpy
  - conda-forge::rasterio
  - conda-forge::tqdm
  - nvidia::cudatoolkit=10.2
  - pytorch::pytorch>=1.10
  - pytorch::torchaudio
  - pytorch::torchvision
