name: hakai-segmentation
channels:
  - defaults
dependencies:
  - python>=3.8,<3.10
  - conda-forge::fire
  - conda-forge::numpy==1.16.4
  - conda-forge::rasterio
  - conda-forge::tqdm
  - pytorch::pytorch>=1.10
  - pytorch::torchvision
