[tool.poetry]
name = "hakai-segmentation"
version = "0.1.0rc2"
description = "Segmentation Tools for Remotely Sensed RPAS Imagery"
authors = ["Taylor Denouden <taylordenouden@gmail.com>"]
license = "MIT"
readme = "README.rst"
repository = "https://github.com/hakaiInstitute/hakai-segmentation"

packages = [
    { include = "hakai_segmentation" }
]

[tool.poetry.scripts]
kom = "hakai_segmentation.main:cli"

[tool.poetry.dependencies]
python = "^3.7"
numpy = "^1.22.2"
rasterio = "^1.2.10"
tqdm = "^4.62.3"
torchvision = "^0.11.3"
torch = "^1.10.2"
fire = "^0.4.0"

[tool.poetry.dev-dependencies]
pytest = "^7.0.1"
Sphinx = "^4.4.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
