name: Build Conda Package

on:
  workflow_call:
    inputs:
      should-upload:
        type: boolean
        required: false
        default: false
        description: Flag to upload to Anaconda

jobs:
  build:
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.9"
          auto-update-conda: true
          activate-environment: my-env
      - name: Install build packages
        run: conda install -y anaconda-client conda-build conda-verify
      - name: Config uploading
        if: inputs.should-upload
        run: conda config --set anaconda_upload yes
      - name: Build package
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          cd conda
          conda build -c pytorch -c conda-forge --output-folder . .
