name: '📦 Conda Publish'

on:
  release:
    types: [ published ]
  push:
    tags:
      - "*"

env:
  ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/_conda-build.yml
    with:
      should-upload: true