name: Python package using Conda

on:
  push:
    branches: [ main ]

jobs:
  build-noarch:
    needs:
      - test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          python-version: 3.9
          auto-update-conda: true
          auto-activate-base: true
    - name: Build noarch package
      run: |
        conda build conda/hakai_segmenetation/meta.yaml
    - name: Upload to Anaconda
      run: |
        conda upload --user hakai-institute ~/anaconda3/conda-bld/noarch/hakai_segmentation-0.1.0rc2-py_0.tar.bz2
