name: Python package using Conda

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Publish to Anaconda
        uses: fcakyon/conda-publish-action@v1.3
        with:
          subdir: 'conda'
          anacondatoken: ${{ secrets.ANACONDA_TOKEN }}
          platforms: 'noarch'
