name: '🧬 Pre Release'

on:
  pull_request:
    branches: [ main, develop ]

concurrency:
  group: ci-pre-release-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        python-version: [ "3.7", "3.8", "3.9" ]
    runs-on: ubuntu-latest
    steps:
      - uses: tayden/hakai-segmentation/.github/workflows/_conda-build.yml@feature/improve-conda-builds
        with:
          python-version: ${{ matrix.python-version }}
